insert into [echo].[DimClient] (ClientID, ClientDesc, TypeClientDesc, VilleClientDesc, CodePostalClient, PaysClientDesc)
values (1, 'Botanechi K.K. 1', 'Indépendants', 'Tokyo', '2567', 'Japon')
,(2, 'Spécial''Affair 4', 'Grossistes', 'Calais', '372840', 'France')
,(3, 'Supras Kids 2', 'Magasins spécialisés', 'Orleans', '270000', 'France')
,(4, 'Ultra DMA 4', 'Grossistes', 'Paris', '450000', 'France')
,(5, 'Country Esquire 1', 'Magasins spécialisés', 'Brighton', NULL, 'Royaume-Uni')
,(6, 'ACME Francfort', 'Détaillants', 'Francfort', '1087794', 'Allemagne')
,(7, 'Passe-Muraille 4', 'Magasins spécialisés', 'Bruxelles', '12576', 'Belgique')
,(8, 'Country Esquire 3', 'Magasins spécialisés', 'Bristol', '643168', 'Royaume-Uni')
,(9, 'Laperière 5', 'Grossistes', 'Sept-Iles', NULL, 'Canada')
,(10, 'Tregoran 2', 'Magasins spécialisés', 'Goteburg', NULL, 'Suede')
,(11, 'Good Style 5', 'Grands magasins', 'Blois', '246270', 'France')
,(12, 'ACME Manchester', 'Détaillants', 'Manchester', NULL, 'Royaume-Uni')
,(13, 'Ligne Intérieure 4', 'Grossistes', 'Grenoble', '228000', 'France')
,(14, 'Berger Equipements 5', 'Grossistes', 'Paris', '450000', 'France')
,(15, 'Ultra DMA 3', 'Grossistes', 'Francfort', '1087794', 'Allemagne')
,(16, 'Excellence', 'Indépendants', 'Montreal', NULL, 'Canada')
,(17, 'InOut Pty 4', 'Grands magasins', 'Sydney', '26928', 'Australie')
,(18, 'Cool Style 3', 'Magasins spécialisés', 'Paris', '450000', 'France')
,(19, 'Home Equipment', 'Indépendants', 'Paris', '450000', 'France')
,(20, 'HomeClub 2', 'Grossistes', 'Strasbourg', '402600', 'France')
,(21, 'Country Esquire 5', 'Magasins spécialisés', 'Chichester', NULL, 'Royaume-Uni')
,(22, 'Grand Stock 1', 'Magasins spécialisés', 'Paris', '450000', 'France')
,(23, 'Home & Style 5', 'Magasins spécialisés', 'La Rochelle', '204072', 'France')
,(24, 'Wally-Mart 1', 'Grands magasins', 'Galway', NULL, 'Royaume-Uni')
,(25, 'ACME Boston', 'Détaillants', 'Boston', '1629882', 'Etats-Unis')
,(26, 'Ligne Intérieure 5', 'Grossistes', 'Paris', '450000', 'France')
,(27, 'Wally-Mart 3', 'Grands magasins', 'Bruxelles', '12576', 'Belgique')
,(28, 'Interiors Ltd', 'Indépendants', 'Singapour', '37904', 'Singapour')
,(29, 'Blauwaren G.m.b.H. 1', 'Grossistes', 'Munich', '978588', 'Allemagne')
,(30, 'Juan''s Shop 2', 'Grossistes', 'Guadalajara', '80480', 'Mexique')
,(31, 'Supras Kids 5', 'Magasins spécialisés', 'Toronto', NULL, 'Canada')
,(32, 'Supremas 5', 'Magasins spécialisés', 'Madrid', '280200', 'Espagne')
,(33, 'Juan''s Shop 1', 'Grossistes', 'Cancun', '63623', 'Mexique')
,(34, 'Botanechi K.K. 2', 'Indépendants', 'Sapporo', '1092', 'Japon')
,(35, 'Ligne Intérieure 1', 'Grossistes', 'Bordeaux', '363011', 'France')
,(36, 'Supremas 1', 'Magasins spécialisés', 'Sevilla', '544765', 'Espagne')
,(37, 'Grand Intérieur 3', 'Grands magasins', 'Strasbourg', '402600', 'France')
,(38, 'Backwoods Equipment Pty', 'Indépendants', 'Sydney', '26928', 'Australie')
,(39, 'Blue Sky 1', 'Grands magasins', 'Melbourne', '25056', 'Australie')
,(40, 'Spécial''Affair 1', 'Grossistes', 'Chamonix', '446400', 'France')
,(41, 'Ultra DMA 5up', 'Grands magasins', 'Poitiers', '516024', 'France')
,(42, 'InOut Pty 3', 'Grands magasins', 'Perth', '72000', 'Australie')
,(43, 'Country Esquire 4', 'Magasins spécialisés', 'Boston', '1629882', 'Etats-Unis')
,(44, 'Grand Intérieur 2', 'Grands magasins', 'Lyon', '414030', 'France')
,(45, 'Supras Kids 3', 'Magasins spécialisés', 'Montreal', NULL, 'Canada')
,(46, 'Blue Sky 4', 'Grands magasins', 'Vancouver', NULL, 'Canada')
,(47, 'ACME Orléans', 'Détaillants', 'Orleans', '270000', 'France')
,(48, 'ACME Deux Ponts', 'Détaillants', 'Paris', '450000', 'France')
,(49, 'Grand Stock 2', 'Magasins spécialisés', 'Hamilton', NULL, 'Canada')
,(50, 'ACME Bracknell', 'Détaillants', 'Bracknell', NULL, 'Royaume-Uni')
,(51, 'ACME Le Puy', 'Détaillants', 'Le Puy', '516096', 'France')
,(52, 'ACME Singapour', 'Détaillants', 'Singapour', '37904', 'Singapour')
,(53, 'Blue Sky 3', 'Grands magasins', 'Boston', '1629882', 'Etats-Unis')
,(54, 'Blue Style', 'Indépendants', 'Nice', '37230', 'France')
,(55, 'Good Style 3', 'Grands magasins', 'Toronto', NULL, 'Canada')
,(56, 'Wilderness Wonderment Ltd', 'Indépendants', 'Bruxelles', '12576', 'Belgique')
,(57, 'Ultra DMA 1', 'Grossistes', 'Barcelona', '228270', 'Espagne')
,(58, 'Midi Line 2', 'Grossistes', 'Rouen', '912000', 'France')
,(59, 'Wally-Mart 2', 'Grands magasins', 'Cork', NULL, 'Royaume-Uni')
,(60, 'Supras Kids 7', 'Grossistes', 'Francfort', '1087794', 'Allemagne')
,(61, 'ACME Églantiers', 'Détaillants', 'Paris', '450000', 'France')
,(62, 'Andes Supplies 3', 'Magasins spécialisés', 'Kamploops', NULL, 'Canada')
,(63, 'Grand Intérieur 5', 'Grands magasins', 'Roubaix', '709200', 'France')
,(64, 'Trees to Seas Ltd', 'Indépendants', 'Londres', NULL, 'Royaume-Uni')
,(65, 'Cool Style 2', 'Magasins spécialisés', 'Paris', '450000', 'France')
,(66, 'Cool Style 5', 'Magasins spécialisés', 'Bordeaux', '363011', 'France')
,(67, 'Country Esquire 2', 'Magasins spécialisés', 'Coventry', '2194407', 'Royaume-Uni')
,(68, 'ACME Tours', 'Détaillants', 'Tours', '296160', 'France')
,(69, 'Supremas 3', 'Magasins spécialisés', 'Barcelona', '228270', 'Espagne')
,(70, 'Home & Style 3', 'Magasins spécialisés', 'Nice', '37230', 'France')
,(71, 'ACME Brixton', 'Détaillants', 'Londres', NULL, 'Royaume-Uni')
,(72, 'Grand Intérieur 1', 'Grands magasins', 'Grenoble', '228000', 'France')
,(73, 'Tregoran 1', 'Magasins spécialisés', 'Stockholm', NULL, 'Suede')
,(74, 'Ultra DMA 2', 'Grossistes', 'Hong Kong', NULL, 'Hong Kong')
,(75, 'ACME Kista', 'Détaillants', 'Stockholm', NULL, 'Suede')
,(76, 'New Fashion 1', 'Grands magasins', 'Puerto Vallarta', '42456', 'Mexique')
,(77, 'Blue Sky 2', 'Grands magasins', 'Anvers', '7250', 'Belgique')
,(78, 'Spécial''Affair 3', 'Grossistes', 'Nantes', '221000', 'France')
,(79, 'OmniChoix 5', 'Grands magasins', 'Wanchai', NULL, 'Hong Kong')
,(80, 'Bergsteiger G.m.b.H.', 'Indépendants', 'Fancfort', '362316', 'Allemagne')
,(81, 'Berger Equipements 1', 'Grossistes', 'Avignon', '504018', 'France')
,(82, 'HomeClub 4', 'Grossistes', 'Paris', '450000', 'France')
,(83, 'Ligne Intérieure 2', 'Grossistes', 'Lyon', '414030', 'France')
,(84, 'Andes Supplies 1', 'Magasins spécialisés', 'Winnipeg', NULL, 'Canada')
,(85, 'New Fashion 3', 'Grands magasins', 'Stockholm', NULL, 'Suede')
,(86, 'Spécial''Affair 2', 'Grossistes', 'Annecy', '818400', 'France')
,(87, 'Juan''s Shop 3', 'Grossistes', 'Monterey', '58007', 'Mexique')
,(88, 'HomeClub 3', 'Grossistes', 'Paris', '450000', 'France')
,(89, 'Blauwaren G.m.b.H. 3', 'Grossistes', 'Bonn', '637452', 'Allemagne')
,(90, 'Midi Line 3', 'Grossistes', 'Lille', '354012', 'France')
,(91, 'ACME Montréal', 'Détaillants', 'Montreal', NULL, 'Canada')
,(92, 'Supremas 2', 'Magasins spécialisés', 'Zaragoza', '364680', 'Espagne')
,(93, 'Blauwaren G.m.b.H. 2', 'Grossistes', 'Hamburg', '112645', 'Allemagne')
,(94, 'Passe-Muraille 3', 'Magasins spécialisés', 'Milford Haven', NULL, 'Royaume-Uni')
,(95, 'ACME Allée du Roy', 'Détaillants', 'Paris', '450000', 'France')
,(96, 'Passe-Muraille 1', 'Magasins spécialisés', 'Valence', '156000', 'France')
,(97, 'Good Style 2', 'Grands magasins', 'Halifax', NULL, 'Canada')
,(98, 'InOut Pty 1', 'Grands magasins', 'Sydney', '26928', 'Australie')
,(99, 'Ligne Intérieure 3', 'Grossistes', 'Grenoble', '228000', 'France')
,(100, 'InOut Pty 2', 'Grands magasins', 'Brisbane', '152000', 'Australie')
,(101, 'OmniChoix 4', 'Grands magasins', 'Shawville', NULL, 'Canada')
,(102, 'Gretz Rennes', 'Détaillants', 'Rennes', '175160', 'France')
,(103, 'Home & Style 4', 'Magasins spécialisés', 'Angouleme', '496093', 'France')