delete from [echo].[DimCommercial]
where [CommercialID] < 33

insert into [echo].[DimCommercial] (CommercialID, CommercialDesc, SuccursaleDesc, PaysDesc)
values (1, 'Douglas Chope', 'Boston', 'États-Unis')
,(2, 'Nicolas Galliot', 'Bordeaux', 'France')
,(3, 'Vincent Marchez', 'Madrid', 'Espagne')
,(4, 'Charles Loo Nam', 'Singapour', 'Singapour')
,(5, 'Jean-claude Bénard', 'Lyon', 'France')
,(6, 'Brian Major', 'Manchester', 'Royaume-Uni')
,(7, 'Malcom Young', 'Melbourne', 'Australie')
,(8, 'Franck Sidi', 'Paris 1', 'France')
,(9, 'Yannick Barbier', 'Vancouver', 'Canada')
,(10, 'Wolfgang Ruzika', 'Francfort', 'Allemagne')
,(11, 'Jean-Pierre Lemoine', 'Limoges', 'France')
,(12, 'Conrad Bergsteige', 'Benelux', 'Belgique')
,(13, 'Olivier Rieffel', 'Marseille', 'France')
,(14, 'Carlos Rodriguez', 'Mexico', 'Mexique')
,(15, 'Eric Soyer', 'Toronto', 'Canada')
,(16, 'Marc Abehassera', 'Paris 1', 'France')
,(17, 'John Dikson', 'Londres', 'Royaume-Uni')
,(18, 'Cedric Saied', 'Orléans', 'France')
,(19, 'Jean-pascal Ancelin', 'Montréal', 'Canada')
,(20, 'Gabrielle Grimaud', 'Paris 2', 'France')
,(21, 'Doug Everhart', 'Boston', 'États-Unis')
,(22, 'Bjorn Flertjan', 'Stockholm', 'Suède')
,(23, 'Kaley Gregson', 'Melbourne', 'Australie')
,(24, 'Sylvie Fleutry', 'Chamonix', 'France')
,(25, 'Hari Krain', 'Tokyo', 'Japon')
,(26, 'Fred Berge', 'Paris 2', 'France')
,(27, 'Alex Medina', 'Madrid', 'Espagne')
,(28, 'Francois lainé', 'Lyon', 'France')
,(29, 'Torey Wandiko', 'Melbourne', 'Australie')
,(30, 'Lee Chan', 'Hong Kong', 'Hong Kong')
,(31, 'Antoine Lapostolle', 'Rouen', 'France')
,(32, 'Skott Keough', 'Londres', 'Royaume-Uni')