insert into [echo].[DimProduit] (ProduitID, ProduitDesc, GammeDesc, TypeProduitDesc)
values (1, 'Pantalon style Battle dress', 'Enfant', 'Habillement')
,(2, 'Adaptateur K7 VHS/VHS-C', 'HI-FI', 'Maison')
,(3, 'Sac Reebrok polyester', 'Lunettes', 'Sport')
,(4, 'Tablette 1/4 de rond', 'Salle de bain', 'Maison')
,(5, 'Sac monumental Adadas', 'Lunettes', 'Sport')
,(6, 'Combinaison de SKI', 'Femme', 'Habillement')
,(7, 'Sac Mike à large ouverture', 'Lunettes', 'Sport')
,(8, 'Blouson 4 bandes Adadas', 'Homme', 'Habillement')
,(9, 'Corde à sauter', 'Musculation', 'Sport')
,(10, 'Sweat bicolore', 'Enfant', 'Habillement')
,(11, 'Chaise style ferme', 'Cuisine', 'Maison')
,(12, 'Blouson de SKI', 'Femme', 'Habillement')
,(13, 'Polo manches courtes', 'Enfant', 'Habillement')
,(14, 'Jean doublé pilou', 'Enfant', 'Habillement')
,(15, 'Porte savon en métal chromé', 'Salle de bain', 'Maison')
,(16, 'Balance électrique Htec', 'Equipement', 'Maison')
,(17, 'Bouilloire électrique Htec', 'Equipement', 'Maison')
,(18, 'Chaussure court cup', 'Homme', 'Habillement')
,(19, 'Armoirette 2 portes', 'Salle de bain', 'Maison')
,(20, 'Parka doublée polaire', 'Enfant', 'Habillement')
,(21, 'Tee shirt brand Adadas', 'Homme', 'Habillement')
,(22, 'Masque de SKI Rock', 'Lunettes', 'Sport')
,(23, 'Télécommande de remplacement', 'HI-FI', 'Maison')
,(24, 'Groupe aspiration Best', 'Equipement', 'Maison')
,(25, 'Patère 3 têtes', 'Cuisine', 'Maison')
,(26, 'Survêtement aukland Adadas', 'Homme', 'Habillement')
,(27, 'Rembobineur K7', 'HI-FI', 'Maison')
,(28, 'Short twill Adadas', 'Homme', 'Habillement')
,(29, 'Paire de poignées de force', 'Musculation', 'Sport')
,(30, 'Porte brosse à dent', 'Salle de bain', 'Maison')
,(31, 'Tabouret à vis', 'Cuisine', 'Maison')
,(32, 'Four grill Htec', 'Equipement', 'Maison')
,(33, 'Parka trecking', 'Femme', 'Habillement')
,(34, 'Sweat brand Adadas', 'Homme', 'Habillement')
,(35, 'Blouson imperméable et déperlant', 'Femme', 'Habillement')
